[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd client && npm install && npm install serve"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd client && ./node_modules/.bin/serve -s dist -l 3000"
